Create python-package.yml
inbo/pywhip pull request #71
Opened 2022-12-16 13:13 UTC by PietrH

This workflow will install Python dependencies, run tests and lint with a variety of Python versions

 For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

## Todo

- [ ] Remove Travis CI
- [ ] Check test coverage, currently test_reporting.py is an empty file
- [ ] consider automatic publishing of releases to PyPI

2022-12-22 16:40 UTC, PietrH commented
Discussed with Peter, currently automatic publishing of github releases to pypi is not a priority. Existing webhook to do this seems broken. Will be removed.

2022-12-22 16:43 UTC, PietrH commented
Removing Travis CI support postponed for now

2022-12-22 16:47 UTC, PietrH commented
Currently coverage is rather low, only at 63%
```
---------- coverage: platform linux, python 3.10.7-final-0 -----------
Name                   Stmts   Miss  Cover
------------------------------------------
pywhip/__init__.py         6      0   100%
pywhip/cli.py             33     20    39%
pywhip/pywhip.py         164    126    23%
pywhip/reporters.py       33     20    39%
pywhip/validators.py     242     13    95%
------------------------------------------
TOTAL                    478    179    63%
```

We can consider increasing this coverage in a future pull request

2022-12-22 16:48 UTC, PietrH commented
Ready for review

2022-12-23 10:34 UTC, peterdesmet requested changes
Nice work! Some minor (mainly) stylistic changes suggested.

2022-12-23 10:34 UTC, peterdesmet commented on .github/workflows/python-package.yml
> +    branches: [ "master" ]
Can you replace this with:

```
- main
- master
```

Same for line 10.

2022-12-23 10:34 UTC, peterdesmet commented on CONTRIBUTING.rst
>     https://travis-ci.org/inbo/pywhip/pull_requests
Update this with GitHub Actions link

2022-12-23 10:34 UTC, peterdesmet commented on .github/workflows/coverage.yml
> +    pull_request:
I think we can run coverage for regular pushes as well, so would updated to:

```
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
```

2022-12-23 10:34 UTC, peterdesmet commented on .github/workflows/coverage.yml
> +    coverage:
This file uses 4 space indents, the other one 2. Would use 2 for both.

2023-01-27 10:15 UTC, merged

2023-01-27 10:16 UTC, PietrH commented
Ok by me to delete the branch